# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Union, Iterable, Optional
from typing_extensions import Literal, Required, Annotated, TypeAlias, TypedDict

from .._types import SequenceNotStr
from .._utils import PropertyInfo
from .tool_param import ToolParam
from .choice_object_param import ChoiceObjectParam
from .stream_options_param import StreamOptionsParam
from .response_format_text_param import ResponseFormatTextParam
from .tool_message_request_param import ToolMessageRequestParam
from .user_message_request_param import UserMessageRequestParam
from .system_message_request_param import SystemMessageRequestParam
from .assistant_message_request_param import AssistantMessageRequestParam
from .response_format_json_object_param import ResponseFormatJsonObjectParam
from .response_format_json_schema_param import ResponseFormatJsonSchemaParam

__all__ = [
    "ChatCreateCompletionParams",
    "CerebrasChatCompletionsExtraBodyCerebrasChatCompletionRequest",
    "CerebrasChatCompletionsExtraBodyCerebrasChatCompletionRequestMessage",
    "CerebrasChatCompletionsExtraBodyCerebrasChatCompletionRequestResponseFormat",
    "CerebrasChatCompletionsExtraBodyCerebrasChatCompletionRequestToolChoice",
    "LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequest",
    "LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequestExtraBody",
    "LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequestMessage",
    "LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequestResponseFormat",
    "LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequestToolChoice",
]


class CerebrasChatCompletionsExtraBodyCerebrasChatCompletionRequest(TypedDict, total=False):
    model: Required[str]

    api_extra_body: Annotated[Optional[object], PropertyInfo(alias="extra_body")]
    """
    Extra body parameters for /v1/chat/completions endpoint. This class is used to
    define additional fields that can be included in the request body that are not
    currently supported by the OpenAI API.
    """

    frequency_penalty: Optional[float]
    """Number between -2.0 and 2.0.

    Positive values penalize new tokens based on their existing frequency in the
    text so far, decreasing the model's likelihood to repeat the same line verbatim.
    """

    logit_bias: Optional[object]
    """Modify the likelihood of specified tokens appearing in the completion.

    Accepts a JSON object that maps tokens (specified by their token ID in the
    tokenizer) to an associated bias value from -100 to 100. Mathematically, the
    bias is added to the logits generated by the model prior to sampling. The exact
    effect will vary per model, but values between -1 and 1 should decrease or
    increase likelihood of selection; values like -100 or 100 should result in a ban
    or exclusive selection of the relevant token.
    """

    logprobs: Optional[bool]
    """Whether to return log probabilities of the output tokens or not.

    If true, returns the log probabilities of each output token returned in the
    content of message.
    """

    max_completion_tokens: Optional[int]
    """
    An upper bound for the number of tokens that can be generated for a completion,
    including visible output tokens and reasoning tokens.
    """

    max_tokens: Optional[int]
    """The maximum number of tokens that can be generated in the chat completion.

    The total length of input tokens and generated tokens is limited by the model's
    context length. This value is now deprecated in favor of max_completion_tokens.
    """

    messages: Optional[Iterable[CerebrasChatCompletionsExtraBodyCerebrasChatCompletionRequestMessage]]

    min_completion_tokens: Optional[int]
    """The minimum number of tokens to generate for a completion.

    If not specified or set to 0, the model will generate as many tokens as it deems
    necessary. Setting to -1 sets to max sequence length.
    """

    min_tokens: Optional[int]
    """The minimum number of tokens to generate for a completion.

    If not specified or set to 0, the model will generate as many tokens as it deems
    necessary. Setting to -1 sets to max sequence length.
    """

    n: Optional[int]
    """How many chat completion choices to generate for each input message.

    Note that you will be charged based on the number of generated tokens across all
    of the choices. Keep n as 1 to minimize costs.
    """

    parallel_tool_calls: Optional[bool]

    presence_penalty: Optional[float]
    """Number between -2.0 and 2.0.

    Positive values penalize new tokens based on whether they appear in the text so
    far, increasing the model's likelihood to talk about new topics.
    """

    response_format: Optional[CerebrasChatCompletionsExtraBodyCerebrasChatCompletionRequestResponseFormat]
    """A response format for text."""

    seed: Optional[int]
    """
    If specified, our system will make a best effort to sample deterministically,
    such that repeated requests with the same `seed` and parameters should return
    the same result. Determinism is not guaranteed.
    """

    service_tier: Optional[Literal["auto", "default"]]

    stop: Union[str, SequenceNotStr[str], None]
    """Up to 4 sequences where the API will stop generating further tokens.

    The returned text will not contain the stop sequence.
    """

    stream: Optional[bool]

    stream_options: Optional[StreamOptionsParam]
    """Options for streaming."""

    temperature: Optional[float]
    """What sampling temperature to use, between 0 and 1.5.

    Higher values like 0.8 will make the output more random, while lower values like
    0.2 will make it more focused and deterministic. We generally recommend altering
    this or `top_p` but not both.
    """

    tool_choice: Optional[CerebrasChatCompletionsExtraBodyCerebrasChatCompletionRequestToolChoice]
    """A choice object."""

    tools: Optional[Iterable[ToolParam]]

    top_logprobs: Optional[int]
    """
    An integer between 0 and 20 specifying the number of most likely tokens to
    return at each token position, each with an associated log probability. logprobs
    must be set to true if this parameter is used.
    """

    top_p: Optional[float]
    """
    An alternative to sampling with temperature, called nucleus sampling, where the
    model considers the results of the tokens with top_p probability mass. So 0.1
    means only the tokens comprising the top 10% probability mass are considered. We
    generally recommend altering this or `temperature` but not both.
    """

    user: Optional[str]
    """
    A unique identifier representing your end-user, which can help Cerebras to
    monitor and detect abuse.
    """

    cf_ray: Annotated[str, PropertyInfo(alias="CF-RAY")]

    x_amz_cf_id: Annotated[str, PropertyInfo(alias="X-Amz-Cf-Id")]

    x_delay_time: Annotated[float, PropertyInfo(alias="X-delay-time")]


CerebrasChatCompletionsExtraBodyCerebrasChatCompletionRequestMessage: TypeAlias = Union[
    SystemMessageRequestParam, UserMessageRequestParam, AssistantMessageRequestParam, ToolMessageRequestParam
]

CerebrasChatCompletionsExtraBodyCerebrasChatCompletionRequestResponseFormat: TypeAlias = Union[
    ResponseFormatTextParam, ResponseFormatJsonObjectParam, ResponseFormatJsonSchemaParam
]

CerebrasChatCompletionsExtraBodyCerebrasChatCompletionRequestToolChoice: TypeAlias = Union[
    Literal["none", "auto", "required"], ChoiceObjectParam
]


class LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequest(TypedDict, total=False):
    model: Required[str]

    api_extra_body: Annotated[
        Optional[LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequestExtraBody], PropertyInfo(alias="extra_body")
    ]
    """Extra body parameters for Llama for /v1/chat/completions."""

    frequency_penalty: Optional[float]
    """Number between -2.0 and 2.0.

    Positive values penalize new tokens based on their existing frequency in the
    text so far, decreasing the model's likelihood to repeat the same line verbatim.
    """

    logit_bias: Optional[object]
    """Modify the likelihood of specified tokens appearing in the completion.

    Accepts a JSON object that maps tokens (specified by their token ID in the
    tokenizer) to an associated bias value from -100 to 100. Mathematically, the
    bias is added to the logits generated by the model prior to sampling. The exact
    effect will vary per model, but values between -1 and 1 should decrease or
    increase likelihood of selection; values like -100 or 100 should result in a ban
    or exclusive selection of the relevant token.
    """

    logprobs: Optional[bool]
    """Whether to return log probabilities of the output tokens or not.

    If true, returns the log probabilities of each output token returned in the
    content of message.
    """

    max_completion_tokens: Optional[int]
    """
    An upper bound for the number of tokens that can be generated for a completion,
    including visible output tokens and reasoning tokens.
    """

    max_tokens: Optional[int]
    """The maximum number of tokens that can be generated in the chat completion.

    The total length of input tokens and generated tokens is limited by the model's
    context length. This value is now deprecated in favor of max_completion_tokens.
    """

    messages: Optional[Iterable[LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequestMessage]]

    min_completion_tokens: Optional[int]
    """The minimum number of tokens to generate for a completion.

    If not specified or set to 0, the model will generate as many tokens as it deems
    necessary. Setting to -1 sets to max sequence length.
    """

    min_tokens: Optional[int]
    """The minimum number of tokens to generate for a completion.

    If not specified or set to 0, the model will generate as many tokens as it deems
    necessary. Setting to -1 sets to max sequence length.
    """

    n: Optional[int]
    """How many chat completion choices to generate for each input message.

    Note that you will be charged based on the number of generated tokens across all
    of the choices. Keep n as 1 to minimize costs.
    """

    parallel_tool_calls: Optional[bool]

    presence_penalty: Optional[float]
    """Number between -2.0 and 2.0.

    Positive values penalize new tokens based on whether they appear in the text so
    far, increasing the model's likelihood to talk about new topics.
    """

    response_format: Optional[LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequestResponseFormat]
    """A response format for text."""

    seed: Optional[int]
    """
    If specified, our system will make a best effort to sample deterministically,
    such that repeated requests with the same `seed` and parameters should return
    the same result. Determinism is not guaranteed.
    """

    service_tier: Optional[Literal["auto", "default"]]

    stop: Union[str, SequenceNotStr[str], None]
    """Up to 4 sequences where the API will stop generating further tokens.

    The returned text will not contain the stop sequence.
    """

    stream: Optional[bool]

    stream_options: Optional[StreamOptionsParam]
    """Options for streaming."""

    temperature: Optional[float]
    """What sampling temperature to use, between 0 and 1.5.

    Higher values like 0.8 will make the output more random, while lower values like
    0.2 will make it more focused and deterministic. We generally recommend altering
    this or `top_p` but not both.
    """

    tool_choice: Optional[LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequestToolChoice]
    """A choice object."""

    tools: Optional[Iterable[ToolParam]]

    top_logprobs: Optional[int]
    """
    An integer between 0 and 20 specifying the number of most likely tokens to
    return at each token position, each with an associated log probability. logprobs
    must be set to true if this parameter is used.
    """

    top_p: Optional[float]
    """
    An alternative to sampling with temperature, called nucleus sampling, where the
    model considers the results of the tokens with top_p probability mass. So 0.1
    means only the tokens comprising the top 10% probability mass are considered. We
    generally recommend altering this or `temperature` but not both.
    """

    user: Optional[str]
    """
    A unique identifier representing your end-user, which can help Cerebras to
    monitor and detect abuse.
    """

    cf_ray: Annotated[str, PropertyInfo(alias="CF-RAY")]

    x_amz_cf_id: Annotated[str, PropertyInfo(alias="X-Amz-Cf-Id")]

    x_delay_time: Annotated[float, PropertyInfo(alias="X-delay-time")]


class LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequestExtraBody(TypedDict, total=False):
    repetition_penalty: Optional[float]


LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequestMessage: TypeAlias = Union[
    SystemMessageRequestParam, UserMessageRequestParam, AssistantMessageRequestParam, ToolMessageRequestParam
]

LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequestResponseFormat: TypeAlias = Union[
    ResponseFormatTextParam, ResponseFormatJsonObjectParam, ResponseFormatJsonSchemaParam
]

LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequestToolChoice: TypeAlias = Union[
    Literal["none", "auto", "required"], ChoiceObjectParam
]

ChatCreateCompletionParams: TypeAlias = Union[
    CerebrasChatCompletionsExtraBodyCerebrasChatCompletionRequest,
    LlamaChatCompletionsExtraBodyCerebrasChatCompletionRequest,
]
